### ISSUE TITLE
Last commit broke background color

### ISSUE THREAD

**Issue by tssm** [charliewilco/ganymede.vim#1]
Hi:

I don't use Ganymede as my terminal color scheme, but I love it on Neovim. With the last commit this is the result:

<img width="1440" alt="screen shot 2017-03-27 at 12 39 47" src="https://cloud.githubusercontent.com/assets/1188977/24364943/af0aa6e6-12ea-11e7-8654-0e76b39baa58.png">

I fixed it by reverting the 13th line, I could change the `src/index.js` file and send a pull request, but wanted to check what do you think.

**Comment by charlespeters** [comment]
oh that was intentional, sorry it broke something for you, i like having a more transparent background.

i'm wondering if there's some options i can pass into it.

**Comment by tssm** [comment]
Transparency doesn't depends on your terminal? Here is how it looks on iTerm with the background set on the scheme

<img width="1552" alt="screen shot 2017-03-27 at 13 56 46" src="https://cloud.githubusercontent.com/assets/1188977/24368015/40e91408-12f5-11e7-8647-7280777b60e2.png">

**Comment by tssm** [comment]
Transparent like this?

<img width="1440" alt="screen shot 2017-03-30 at 10 42 53 2" src="https://cloud.githubusercontent.com/assets/1188977/24507038/c9ecb768-1535-11e7-9c2d-31780772ade6.png">

**Comment by charlespeters** [comment]
@tssm i meant like define the plugin like normal but have a setting like
`set ganymedebkg null`

i'm not too skilled with vimL which is why i borrowed a template from @trevordmiller. i'm totally open to suggestions or pull requests.

**Comment by tssm** [comment]
I can send a pull request but I am still confused. If you declare the background color with `hi Normal guibg=#093750 ...` (in your `s:highlight_helper` function) you lost the terminal transparency? Or you want to avoid to always set `#093750` as `l:background_color` when `a:3` is empty?

Sorry, English is my second language ^^
